### ISSUE TITLE
NoteActivity OOM

### ISSUE THREAD

**Issue by 1hakr** [1hakr/AnExplorer#19]
NoteActivity.java line 131
dev.dworks.apps.anexplorer.NoteActivity.onOptionsItemSelected

java.lang.OutOfMemoryError
       at android.text.SpannableStringBuilder.toString(SpannableStringBuilder.java:933)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:9007)
       at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:979)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:688)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
       at android.widget.TextView.setText(TextView.java:3554)
       at android.widget.TextView.setText(TextView.java:3425)
       at android.widget.EditText.setText(EditText.java:80)
       at android.widget.TextView.setText(TextView.java:3400)
       at dev.dworks.apps.anexplorer.NoteActivity.onOptionsItemSelected(NoteActivity.java:131)
       at android.app.Activity.onMenuItemSelected(Activity.java:2534)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:350)
       at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
       at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
       at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:556)
       at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
       at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:596)
       at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:145)
       at android.view.View.performClick(View.java:4084)
       at android.view.View$PerformClick.run(View.java:16966)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4795)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by 1hakr** [comment]
fixed in version 2.6
