### ISSUE TITLE
Not compatible with Oreo

### ISSUE THREAD

**Issue by Hanzala717** [1hakr/AnExplorer#85]
Process: dev.dworks.apps.anexplorer.pro, PID: 32430
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at dev.dworks.apps.anexplorer.misc.AsyncTask$3.done(AsyncTask.java:326)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider dev.dworks.apps.anexplorer.provider.RecentsProvider from ProcessRecord{61e61a 32430:dev.dworks.apps.anexplorer.pro/u0a153} (pid=32430, uid=10153) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.readException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1888)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2053)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:2042)
        at dev.dworks.apps.anexplorer.misc.RootsCache.loadRootsForAuthority(RootsCache.java:283)
        at dev.dworks.apps.anexplorer.misc.RootsCache.access$900(RootsCache.java:67)
        at dev.dworks.apps.anexplorer.misc.RootsCache$UpdateTask.handleDocumentsProvider(RootsCache.java:268)
        at dev.dworks.apps.anexplorer.misc.RootsCache$UpdateTask.doInBackground(RootsCache.java:224)
        at dev.dworks.apps.anexplorer.misc.RootsCache$UpdateTask.doInBackground(RootsCache.java:180)
        at dev.dworks.apps.anexplorer.misc.AsyncTask$2.call(AsyncTask.java:313)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by 1hakr** [comment]
This is fixed in the upcoming version 4.0.0
